/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ColumnGroup: typeof import('primevue/columngroup')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataTableMapping: typeof import('./src/components/DataTableMapping.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    DataViewLayoutOptions: typeof import('primevue/dataviewlayoutoptions')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/shared/Footer.vue')['default']
    Header: typeof import('./src/components/shared/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingSpinner: typeof import('./src/components/shared/LoadingSpinner.vue')['default']
    MappingList: typeof import('./src/components/shared/MappingList.vue')['default']
    MappingTable: typeof import('./src/components/MappingTable.vue')['default']
    Menu: typeof import('./src/components/shared/Menu.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MenuHeader: typeof import('./src/components/shared/MenuHeader.vue')['default']
    Message: typeof import('primevue/message')['default']
    Modal: typeof import('./src/components/shared/Modal.vue')['default']
    Navigator: typeof import('./src/components/shared/Navigator.vue')['default']
    ProjectList: typeof import('./src/components/shared/ProjectList.vue')['default']
    ProjectTable: typeof import('./src/components/ProjectTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('primevue/row')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
