version: '3.3'
services:
  miracum-mapper-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miracum-mapper-frontend
    ports:
      - '443:443'
    networks:
      - miracum_public_network
networks:
  miracum_public_network:
    external: true
