version: '3.3'
services:
  miracum-mapper-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miracum-mapper-frontend
    ports:
      - '443:443'
    networks:
      - shared_network

networks:
  shared_network:
    external: true
