/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check if the server is running
         * @description This endpoint can be used to check if the server is running. It returns a simple pong message.
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all projects
         * @description Get all projects with pagination. Sorting can also be specified by query parameters.
         */
        get: operations["getAllProjects"];
        /**
         * Update the project information
         * @description Update the project information. Does not update the permissions for the users or the code system roles (the columns in the mapping table).
         */
        put: operations["updateProject"];
        /**
         * Create a new project
         * @description Create a new project with permissions and code system roles (the columns in the mapping table). Code system roles can not be changed after creation.
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project details
         * @description Get the project details by ID including the list of project permissions and code system roles (the columns in the mapping table)
         */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /**
         * Delete a project
         * @description Delete a project by ID. This will also delete all mappings and elements of the project as well as the permissions for the project and the code system roles.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get permissions for a project
         * @description Get all permissions for a project by project ID.
         */
        get: operations["getAllPermissions"];
        /**
         * Update a project permission for a user
         * @description Update a project permission for a user by the user ID
         */
        put: operations["updatePermission"];
        /**
         * Create a new project permission for user
         * @description Create a new project permission for a user by the user ID.
         */
        post: operations["createPermission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/permissions/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project permission for a specific user
         * @description Get the project permission for a specific user by the user ID.
         */
        get: operations["getPermission"];
        put?: never;
        post?: never;
        /**
         * Delete a project permission for a user
         * @description Delete a project permission for a user by the user ID
         */
        delete: operations["deletePermission"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/codesystem-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all code system roles for a project
         * @description Get all code system roles (columns in the mapping table) for a project by project ID
         */
        get: operations["getAllCodeSystemRoles"];
        /**
         * Update a code system role by ID
         * @description Update name or type from a code system role (column in the mapping table) by ID
         */
        put: operations["updateCodeSystemRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/codesystem-roles/{codesystem-role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a code system role by ID
         * @description Get a code system role (column in the mapping table) by ID
         */
        get: operations["getCodeSystemRole"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all mappings for a project by project ID
         * @description Get all mappings for a project by project ID. The mappings include all elements with concepts. Paging and sorting can be specified by query parameters.
         */
        get: operations["getAllMappings"];
        /**
         * Update a mapping and its elements by their concept IDs
         * @description Update a mapping by ID and all included elements by using the corresponding concept IDs.
         */
        put: operations["updateMapping"];
        /**
         * Create a new mapping for a project
         * @description Create a new mapping for a project by project ID including all needed elements (specified by code_system_roles from the corresponding project)
         */
        post: operations["createMapping"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a mapping and its elements by their concept IDs
         * @description Update a mapping by ID and all included elements by using the corresponding concept IDs. Missing elements are deleted.
         */
        patch: operations["patchMapping"];
        trace?: never;
    };
    "/projects/{project_id}/mappings/{mapping_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a mapping with its elements by ID
         * @description Get a mapping by ID and all included elements. The elements include the concept with the system-id.
         */
        get: operations["getMapping"];
        put?: never;
        post?: never;
        /**
         * Delete a mapping and its elements by ID
         * @description Delete a mapping by ID and all included elements.
         */
        delete: operations["deleteMapping"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/codesystems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all code systems
         * @description Get all code systems.
         */
        get: operations["getAllCodeSystems"];
        /**
         * Update a code system by ID
         * @description Update a code system by ID. Only admins can update code systems.
         */
        put: operations["updateCodeSystem"];
        /**
         * Create a new code system
         * @description Create a new code system. Only admins can create code systems.
         */
        post: operations["createCodeSystem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/codesystems/{codesystem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a code system by ID
         * @description Get a code system by ID.
         */
        get: operations["getCodeSystem"];
        put?: never;
        post?: never;
        /**
         * Delete a code system by ID
         * @description Delete a code system by ID. Only admins can delete code systems.
         */
        delete: operations["deleteCodeSystem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/codesystems/{codesystem_id}/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all concepts for a code system by ID
         * @description Get all concepts for a code system by ID. Paging and sorting can be specified by query parameters.
         */
        get: operations["getAllConcepts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BaseProject: {
            name: string;
            version: string;
            description: string;
            equivalence_required: boolean;
            status_required: boolean;
        };
        UpdateProject: components["schemas"]["BaseProject"] & {
            /** Format: int32 */
            id: number;
        };
        Project: components["schemas"]["UpdateProject"] & {
            modified: string;
            created: string;
        };
        CreateProjectDetails: components["schemas"]["BaseProject"] & {
            project_permissions?: components["schemas"]["SendProjectPermission"][];
            code_system_roles: components["schemas"]["CreateCodeSystemRole"][];
        };
        ProjectDetails: components["schemas"]["Project"] & {
            project_permissions?: components["schemas"]["ProjectPermission"][];
            code_system_roles: components["schemas"]["CodeSystemRole"][];
        };
        SendProjectPermission: {
            user_id: string;
            /** @enum {string} */
            role: "reviewer" | "project_owner" | "editor";
        };
        ProjectPermission: components["schemas"]["SendProjectPermission"] & {
            user_name: string;
        };
        CreateCodeSystemRole: {
            name: string;
            /** Format: int32 */
            system: number;
            /** @enum {string} */
            type: "source" | "target";
        };
        UpdateCodeSystemRole: {
            /** Format: int32 */
            id: number;
            name: string;
            /** @enum {string} */
            type: "source" | "target";
        };
        CodeSystemRole: components["schemas"]["UpdateCodeSystemRole"] & {
            system: {
                /** Format: int32 */
                id: number;
                name: string;
                version: string;
            };
        };
        CreateMapping: {
            /** @enum {string} */
            equivalence?: "related-to" | "equivalent" | "source-is-narrower-than-target" | "source-is-broader-than-target" | "not-related";
            /** @enum {string} */
            status?: "active" | "inactive" | "pending";
            comment?: string;
            elements?: components["schemas"]["Element"][];
        };
        UpdateMapping: components["schemas"]["CreateMapping"] & {
            /** Format: int64 */
            id: number;
        };
        Mapping: components["schemas"]["UpdateMapping"] & {
            elements: components["schemas"]["FullElement"][];
            created: string;
            modified: string;
        };
        Element: {
            /** Format: int32 */
            codeSystemRole?: number;
            /** Format: int64 */
            concept?: number;
        };
        FullElement: components["schemas"]["Element"] & {
            concept?: components["schemas"]["Concept"];
        };
        Concept: {
            /** Format: int64 */
            id: number;
            code: string;
            meaning: string;
        };
        CreateCodeSystem: {
            uri: string;
            version: string;
            name: string;
            title?: string;
            description?: string;
            author?: string;
        };
        CodeSystem: components["schemas"]["CreateCodeSystem"] & {
            /** Format: int32 */
            id: number;
        };
        ErrorResponse: string;
    };
    responses: {
        /** @description Invalid Request (e.g., negative id supplied, invalid body (e.g. missing field) or query parameters) */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": string;
            };
        };
        /** @description Internal Server Error due to database or implementation errors */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": string;
            };
        };
    };
    parameters: {
        /** @description The ID of the project */
        project_id: number;
        /** @description The ID of the user */
        user_id: string;
        /** @description The ID of the code system role */
        "codesystem-role_id": number;
        /** @description The ID of the mapping */
        mapping_id: number;
        /** @description The ID of the Codesystem */
        codesystem_id: number;
        /** @description Page number (must be a positive integer) */
        page: number;
        /** @description Number of items per page (minimum 1, maximum 100) */
        pageSize: number;
        /** @description Order of sorting (asc or desc) */
        sortOrder: "asc" | "desc";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example pong */
                        message?: string;
                    };
                };
            };
        };
    };
    getAllProjects: {
        parameters: {
            query?: {
                /** @description Page number (must be a positive integer) */
                page?: components["parameters"]["page"];
                /** @description Number of items per page (minimum 1, maximum 100) */
                pageSize?: components["parameters"]["pageSize"];
                /** @description Field to sort sortBy */
                sortBy?: "name" | "dateCreated" | "id";
                /** @description Order of sorting (asc or desc) */
                sortOrder?: components["parameters"]["sortOrder"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Page not found (e.g., page number too high) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProject"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Exception */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDetails"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Validation Exception */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPermission"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    updatePermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendProjectPermission"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPermission"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Exception */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    createPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendProjectPermission"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPermission"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Exception */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
                /** @description The ID of the user */
                user_id: components["parameters"]["user_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPermission"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    deletePermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
                /** @description The ID of the user */
                user_id: components["parameters"]["user_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPermission"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllCodeSystemRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSystemRole"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    updateCodeSystemRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCodeSystemRole"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSystemRole"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or codesystem-role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getCodeSystemRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
                /** @description The ID of the code system role */
                "codesystem-role_id": components["parameters"]["codesystem-role_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSystemRole"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or codesystem-role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllMappings: {
        parameters: {
            query?: {
                /** @description Page number (must be a positive integer) */
                page?: components["parameters"]["page"];
                /** @description Number of items per page (minimum 1, maximum 100) */
                pageSize?: components["parameters"]["pageSize"];
                /** @description Field to sort by */
                sortBy?: "id" | "equivalence" | "status" | "comment" | "created" | "modified";
                /** @description Order of sorting (asc or desc) */
                sortOrder?: components["parameters"]["sortOrder"];
            };
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Page not found (e.g., page number too high) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    updateMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMapping"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or Mapping not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    createMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMapping"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Exception */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    patchMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMapping"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or Mapping not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
                /** @description The ID of the mapping */
                mapping_id: components["parameters"]["mapping_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or Mapping not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project */
                project_id: components["parameters"]["project_id"];
                /** @description The ID of the mapping */
                mapping_id: components["parameters"]["mapping_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or Mapping not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllCodeSystems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSystem"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Project or codesystem-role not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    updateCodeSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeSystem"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSystem"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Codesystem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    createCodeSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCodeSystem"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSystem"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description CodeSystem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Exception */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getCodeSystem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the Codesystem */
                codesystem_id: components["parameters"]["codesystem_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSystem"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description CodeSystem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteCodeSystem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the Codesystem */
                codesystem_id: components["parameters"]["codesystem_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSystem"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Codesystem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllConcepts: {
        parameters: {
            query?: {
                /** @description Page number (must be a positive integer) */
                page?: components["parameters"]["page"];
                /** @description Number of items per page (minimum 1, maximum 100) */
                pageSize?: components["parameters"]["pageSize"];
                /** @description Field to sort sortBy */
                sortBy?: "code" | "meaning";
                /** @description Order of sorting (asc or desc) */
                sortOrder?: components["parameters"]["sortOrder"];
                /** @description search for the code */
                codeSearch?: string;
                /** @description search for meaning */
                meaningSearch?: string;
            };
            header?: never;
            path: {
                /** @description The ID of the Codesystem */
                codesystem_id: components["parameters"]["codesystem_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Concept"][];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description CodeSystem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
